# Generated by Django 4.0.5 on 2022-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaYardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
